CREATE TABLE postos(
id BIGINT NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
local VARCHAR(100) NOT NULL,
gasolina NUMERIC(5,2),
alcool NUMERIC(5,2),
inativo TINYINT DEFAULT 0,
PRIMARY KEY(id))